# Notice the use of env variables by the use of variable subsitution like so
# image: "postgres:${POSTGRES_VERSION}"
# for example. This repo comes bootstrapped to run out of the box by running the command
# docker-compose --env-file .env up
# which will use the environment variables defined in .env in this docker-compose file
# and some containers defined here with the use of the env_file: attribute.
#
# for helpful links that helped me create this solution of env variables see here;
# https://docs.docker.com.xy2401.com/compose/compose-file/#variable-substitution
# https://docs.docker.com.xy2401.com/compose/environment-variables/
# https://mkyong.com/python/how-to-get-an-environment-variable-in-python/
version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8100:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.6.50
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379