# Generated by Django 4.0.4 on 2022-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='emails',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
