# Generated by Django 4.0.4 on 2022-06-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_orderitems_orderitem_order_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='emails',
            new_name='email',
        ),
    ]
